### ISSUE TITLE
which one is positive one sample and negative sample in your work?

### ISSUE THREAD

**Issue by timchen91stu** [alinlab/CSI#2]
In SimCLR that considers one image from different augmentations as positive to each other，different image as negative.
could you please clearly show who is positive one in your work? who is negative one in your work?

**Comment by sangwoomo** [comment]
Hi, same as SimCLR, we use the same images with different augmentations as positive samples and different images as negative samples.
However, unlike SimCLR, we think some of the augmentations produce different (or distributionally-shifted) ones from the original.
In original SimCLR, they simply ignored those augmentations (e.g., rotation) since considering them as positive samples degrade the performance.
In contrast, we found that treating them as the negative ones _in addition to_ the original negative samples (i.e., different images) improves the OOD detection performance.

Formally, say x1 x2 are two images, T1 T2 are two augmentations (that produces positive samples), and S is a strong (or distribution shifting) transformation.

Then, the original SimCLR ignores S1 S2 and think
- T1(x1), T2(x1) are positive
- T1(x1), T3(x2) are negative

and ours think
- in addition to the upper assumptions, T1(x1), T2(**S**(x1)) are also negative

Hope this clarifies your question.
Please let us know if you have any unclear points!
