### ISSUE TITLE
Questions About Multi-Labeled OOD

### ISSUE THREAD

**Issue by wjun0830** [alinlab/CSI#32]
Are the results from multi-labeled OOD were yielded at the same epoch?
ex) results from cifar10 - svhn, imagenet-resize, lsun-resize, lsun-fix.... 
or are each of them are from the best AUROC epoch during training?

There might be difference in best epoch for each out-dataset.

Thanks.

**Comment by sangwoomo** [comment]
Hi, since our goal is to train a universal detector for all OOD datasets (as we don't know which dataset the test sample belongs to), we simply use the last model.
As you pointed, the performance curve of each OOD dataset may differ, and it would be an interesting direction to investigate that and improve the model for all cases.

**Comment by wjun0830** [comment]
Thanks for fast and kind replies

2021년 4월 8일 (목) 오후 2:38, Sangwoo Mo ***@***.***>님이 작성:
