### ISSUE TITLE
how to identify

### ISSUE THREAD

**Issue by chenneng** [alinlab/CSI#7]
I don't understand how your scripts identify whether the test samples belong to the in-distribution or not. It seems taking the feature of training set into consideration when testing,which make me confused

**Comment by sangwoomo** [comment]
Hi, we give training features for the score function since some scores may require them (e.g., CSI computes the maximum cosine similarity over the training samples `max_m sim(x, x_m)`). It is reasonable to assume the training features are accessible, as the training in-distribution samples are known for the user. Furthermore, we validate that keeping only a small amount of training samples (i.e., small memory/computation) is enough, as shown in Appendix E of our paper.
